### ISSUE TITLE
Adapt for mobile

### ISSUE THREAD

**Issue by razbakov** [officert/vue-slideout-panel#3]
Panel is not usable on mobile phones

**Comment by officert** [comment]
@razbakov good call, I added support in V0.7.0 https://github.com/officert/vue-slideout-panel/releases/tag/0.7.0

Basically I'm dynamically creating a stylesheet for each panels with a media query of 
```css
@media screen and (max-width:${panel.styles.width}) {
  #${panel.cssId} {
    width: 100% !important;
  }
}
```

so that once your browser sizes gets to the width of the panel it'll switch to 100% width.
